// DRC Virtual Golf Caddie — clean Glide baseline
const HOLES=[{hole:1,par:5,si:5,front:480,centre:498,back:512},{hole:2,par:4,si:11,front:356,centre:369,back:382},{hole:3,par:3,si:15,front:142,centre:151,back:160},{hole:4,par:4,si:1,front:396,centre:410,back:423},{hole:5,par:5,si:7,front:475,centre:491,back:506},{hole:6,par:3,si:17,front:128,centre:139,back:150},{hole:7,par:4,si:9,front:348,centre:361,back:374},{hole:8,par:4,si:3,front:382,centre:397,back:410},{hole:9,par:4,si:13,front:335,centre:349,back:362},{hole:10,par:4,si:6,front:368,centre:381,back:394},{hole:11,par:5,si:4,front:492,centre:508,back:523},{hole:12,par:3,si:16,front:151,centre:162,back:173},{hole:13,par:4,si:10,front:346,centre:360,back:373},{hole:14,par:4,si:2,front:401,centre:416,back:429},{hole:15,par:5,si:8,front:485,centre:501,back:517},{hole:16,par:3,si:18,front:121,centre:132,back:143},{hole:17,par:4,si:12,front:355,centre:369,back:382},{hole:18,par:4,si:14,front:361,centre:375,back:389}];
const HOLE_MAP_SHAPES=['wide','dogleg-left','short','dogleg-right','s','short','left','right','narrow','dogleg-left','wide','short','right','dogleg-right','s','short','left','narrow'];
let bag=JSON.parse(localStorage.getItem('drcBag')||'null')||{'Driver':230,'3 Wood':210,'5 Wood':195,'4 Iron':180,'5 Iron':170,'6 Iron':160,'7 Iron':150,'8 Iron':140,'9 Iron':130,'PW':115,'GW':100,'SW':85,'LW':70};let settings=JSON.parse(localStorage.getItem('drcSettings')||'null')||{player:'Dale',caddie:'Pete',hcp:18,units:'m'};let scores=JSON.parse(localStorage.getItem('drcScores')||'null')||{};let currentHole=0,gpsLat=null,gpsLon=null,gpsAcc=null,gpsAlt=null,weatherTemp=20,weatherWind=0,weatherWindDir='N',selectedWindDir='N',selectedElev=0,selectedLie='fairway',bagUnits='m',practiceData={good:0,left:0,right:0,short:0,long:0},warmupState=[false,false,false,false,false,false,false,false],routineState=[false,false,false,false,false,false,false,false],recognition=null;
function drcNav(name){document.querySelectorAll('.view').forEach(v=>v.style.display='none');document.querySelectorAll('.bnav-btn').forEach(b=>b.classList.remove('active'));let el=document.getElementById(name+'View');if(el)el.style.display='flex';let nb=document.getElementById('nav-'+name);if(nb)nb.classList.add('active');({round:initRound,caddie:initCaddie,bag:initBag,more:initMore,scorecard:renderScorecard,practice:renderPractice,warmup:renderWarmup,routines:renderRoutine}[name]||(()=>{}))();}
function unitDist(m){return settings.units==='y'?Math.round(m*1.094):Math.round(m)}function unitLabel(){return settings.units==='y'?'y':'m'}function nearestClub(d){let best='Driver',gap=Infinity;Object.entries(bag).forEach(([n,x])=>{let g=Math.abs(x-d);if(g<gap){gap=g;best=n}});return best}
function initRound(){setTimeout(updateWindMarker,0);let h=HOLES[currentHole],u=unitLabel();let map=document.querySelector('.hole-map');if(map){map.className='hole-map shape-'+HOLE_MAP_SHAPES[currentHole];}document.getElementById('holeLabel').textContent='Hole '+h.hole+' · Par '+h.par;document.getElementById('holeSI').textContent='Stroke Index '+h.si;['Front','Centre','Back'].forEach(k=>document.getElementById('dist'+k).textContent=unitDist(h[k.toLowerCase()]));document.querySelectorAll('.dist-unit').forEach(e=>e.textContent=u);let sc=scores['h'+h.hole]||{};['score','putts','pen'].forEach(k=>document.getElementById('sc-'+k).textContent=sc[k]||0);['gir','fw'].forEach(k=>document.getElementById('sc-'+k).textContent=sc[k]===true?'✓':sc[k]===false?'✗':'-');document.getElementById('recClub').textContent=nearestClub(h.centre);document.getElementById('recPlays').textContent='Plays '+unitDist(h.centre)+' '+u+' · '+(weatherWind?'wind '+weatherWind+' km/h':'calm');updateWeatherDisplay()}
function nextHole(){currentHole=Math.min(17,currentHole+1);initRound()}function prevHole(){currentHole=Math.max(0,currentHole-1);initRound()}function adjScore(f,d){let k='h'+HOLES[currentHole].hole,s=scores[k]||{};s[f]=Math.max(0,(s[f]||0)+d);scores[k]=s;localStorage.setItem('drcScores',JSON.stringify(scores));initRound()}function toggleBool(f,v){let k='h'+HOLES[currentHole].hole,s=scores[k]||{};s[f]=v;scores[k]=s;localStorage.setItem('drcScores',JSON.stringify(scores));initRound()}
function initCaddie(){document.getElementById('calcTemp').value=weatherTemp;document.getElementById('calcWind').value=weatherWind}function setWind(b){document.querySelectorAll('.compass-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');selectedWindDir=b.dataset.dir}function setElev(b){document.querySelectorAll('#elevToggle .toggle-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');selectedElev=Number(b.dataset.elev||0)}function setLie(b){document.querySelectorAll('#lieToggle .toggle-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');selectedLie=b.dataset.lie||'fairway'}
function shotAdvice(d,w,t,a){let p=d;p+=selectedElev*d*.05;if(['N','NNE','NNW','NE','NW'].includes(selectedWindDir))p+=w*.7;if(['S','SSE','SSW','SE','SW'].includes(selectedWindDir))p-=w*.45;if(t<15)p+=d*.03;if(t>30)p-=d*.02;if(a>300)p-=d*Math.min(.08,a/10000);if(selectedLie.includes('rough'))p*=1.05;if(selectedLie==='bunker')p*=1.1;return Math.max(1,Math.round(p))}function calcShot(){let d=Number(document.getElementById('calcDist').value)||150,w=Number(document.getElementById('calcWind').value)||0,t=Number(document.getElementById('calcTemp').value)||20,a=Number(document.getElementById('calcAlt').value)||0,p=shotAdvice(d,w,t,a),club=nearestClub(p);document.getElementById('calcResult').style.display='block';document.getElementById('calcResultDist').textContent=p+' m';document.getElementById('calcResultClub').textContent=club;document.getElementById('calcResultAdvice').textContent='Plays about '+p+' m from the '+selectedLie+'. '+selectedWindDir+' wind. Commit to '+club+'.';return{plays:p,club}}
function speak(t){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang='en-AU';u.rate=.95;u.pitch=1;window.speechSynthesis.speak(u)}function askPete(){let SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){let r=calcShot(),m='I recommend '+r.club+'. It is playing about '+r.plays+' metres.';document.getElementById('peteResponseCard').style.display='block';document.getElementById('peteResponseText').textContent=m;let ca=document.getElementById('caddieAnswerText');if(ca)ca.textContent=m;speak(m);return}recognition=new SR();recognition.lang='en-AU';recognition.interimResults=false;document.getElementById('peteStatus').textContent='Listening…';recognition.onresult=e=>{let heard=e.results[0][0].transcript,txt=heard.toLowerCase();document.getElementById('peteHeardText').textContent='Heard: '+heard;let cs=document.getElementById('caddieSpokenText');if(cs)cs.textContent='Heard: '+heard;let nums=txt.match(/\d+/);if(nums)document.getElementById('calcDist').value=nums[0];if(txt.includes('light rough'))selectedLie='light rough';else if(txt.includes('deep rough'))selectedLie='deep rough';else if(txt.includes('rough'))selectedLie='rough';else if(txt.includes('bunker'))selectedLie='bunker';else if(txt.includes('fairway'))selectedLie='fairway';let windText='';if(/left (to|or) right|left[- ]to[- ]right/.test(txt)){selectedWindDir='L→R';windText='Wind is moving left to right, so allow for the crosswind. '}else if(/right (to|or) left|right[- ]to[- ]left/.test(txt)){selectedWindDir='R→L';windText='Wind is moving right to left, so allow for the crosswind. '}else if(txt.includes('headwind')||txt.includes('into the wind')){selectedWindDir='N';windText='You are into the wind. '}else if(txt.includes('tailwind')||txt.includes('wind behind')){selectedWindDir='S';windText='The wind is helping. '}let pin=txt.includes('pin')&&(txt.includes('back')?'back':txt.includes('front')?'front':txt.includes('center')||txt.includes('centre')?'centre':'');let d=Number(document.getElementById('calcDist').value)||150,w=Number(document.getElementById('calcWind').value)||weatherWind||0,t=Number(document.getElementById('calcTemp').value)||weatherTemp||20,a=Number(document.getElementById('calcAlt').value)||0,p=shotAdvice(d,w,t,a),club=nearestClub(p);let lieText=selectedLie==='fairway'?'':('From the '+selectedLie+', favour clean contact. ');let pinText=pin?('Pin is '+pin+'. '):'';let m='Playing about '+p+' metres. '+lieText+windText+pinText+'I recommend '+club+'. Commit to the shot.';document.getElementById('peteResponseCard').style.display='block';document.getElementById('peteResponseText').textContent=m;let ca=document.getElementById('caddieAnswerText');if(ca)ca.textContent=m;document.getElementById('peteStatus').textContent='Tap to speak';speak(m)};recognition.onerror=()=>document.getElementById('peteStatus').textContent='Could not hear you — tap and try again';recognition.start()}
function updateWeatherDisplay(){let t='☀️ '+Math.round(weatherTemp)+'°C | '+Math.round(weatherWind)+' km/h',h=document.getElementById('homeWeather'),r=document.getElementById('roundWeather');if(h)h.textContent=t;if(r)r.textContent='☀️ '+Math.round(weatherTemp)+'°C'}function updateGPSInfo(){let e=document.getElementById('gpsInfo');if(e)e.innerHTML=gpsLat==null?'GPS searching…':'Latitude: '+gpsLat.toFixed(5)+'<br>Longitude: '+gpsLon.toFixed(5)+'<br>Accuracy: '+Math.round(gpsAcc||0)+' m'}function startGPS(){if(!navigator.geolocation)return;navigator.geolocation.watchPosition(p=>{gpsLat=p.coords.latitude;gpsLon=p.coords.longitude;gpsAcc=p.coords.accuracy;gpsAlt=p.coords.altitude;let b=document.getElementById('gpsBadge');if(b){b.textContent='📡 GPS LIVE · ±'+Math.round(gpsAcc)+'m';b.classList.remove('searching')}updateGPSInfo();fetchLiveWind()},()=>{let b=document.getElementById('gpsBadge');if(b)b.textContent='📡 GPS UNAVAILABLE'},{enableHighAccuracy:true,maximumAge:3000,timeout:15000})}
function initBag(){renderBagList()}function renderBagList(){let html='',u=bagUnits==='y';Object.entries(bag).forEach(([name,dist])=>{let d=u?Math.round(dist*1.094):dist;html+='<div class="club-row"><span class="club-row-name">'+name+'</span><div class="stepper"><button class="step-btn" onclick="adjustClub(\''+name+'\',-5)">−</button><span class="step-val">'+d+'</span><button class="step-btn" onclick="adjustClub(\''+name+'\',5)">+</button></div><span>'+(u?'y':'m')+'</span></div>'});document.getElementById('bagList').innerHTML=html}function adjustClub(n,d){if(bagUnits==='y')d=Math.round(d/1.094);bag[n]=Math.max(0,(bag[n]||0)+d);renderBagList()}function setUnits(u){bagUnits=u;document.getElementById('bagM').classList.toggle('active',u==='m');document.getElementById('bagY').classList.toggle('active',u==='y');renderBagList()}function setUnitsAll(u){settings.units=u;bagUnits=u;document.getElementById('setM').classList.toggle('active',u==='m');document.getElementById('setY').classList.toggle('active',u==='y')}function saveBag(){localStorage.setItem('drcBag',JSON.stringify(bag));document.getElementById('bagSaved').textContent='✅ Bag saved!'}
function initMore(){let ag=document.getElementById('antiGlareBtn');if(ag)ag.textContent=document.body.classList.contains('antiglare')?'ON':'OFF';document.getElementById('profileName').textContent=settings.player;document.getElementById('profileCaddie').textContent='Caddie: '+settings.caddie+' · HCP: '+settings.hcp;document.getElementById('settingsCaddie').value=settings.caddie;document.getElementById('settingsPlayer').value=settings.player;document.getElementById('settingsHCP').value=settings.hcp;updateGPSInfo()}function saveSettings(){settings.caddie=document.getElementById('settingsCaddie').value||'Pete';settings.player=document.getElementById('settingsPlayer').value||'Dale';settings.hcp=parseFloat(document.getElementById('settingsHCP').value)||18;localStorage.setItem('drcSettings',JSON.stringify(settings));initMore()}
function renderScorecard(){let html='<thead><tr><th>Hole</th><th>Par</th><th>Score</th><th>Putts</th><th>GIR</th><th>FW</th><th>Pen</th></tr></thead><tbody>',tp=0,ts=0;HOLES.forEach(h=>{let s=scores['h'+h.hole]||{};tp+=h.par;ts+=s.score||0;html+='<tr><td>'+h.hole+'</td><td>'+h.par+'</td><td>'+(s.score||'-')+'</td><td>'+(s.putts||'-')+'</td><td>'+(s.gir===true?'✓':s.gir===false?'✗':'-')+'</td><td>'+(s.fw===true?'✓':s.fw===false?'✗':'-')+'</td><td>'+(s.pen||0)+'</td></tr>'});document.getElementById('scorecardTable').innerHTML=html+'</tbody>';document.getElementById('scoreTotals').textContent='Par '+tp+' · Score '+(ts||'--')}function shareScorecard(){let t='DRC Golf Scorecard\n';HOLES.forEach(h=>t+='H'+h.hole+' Par'+h.par+': '+((scores['h'+h.hole]||{}).score||'-')+'\n');if(navigator.share)navigator.share({title:'DRC Scorecard',text:t})}
function renderPractice(){}function setPracticeType(b){document.querySelectorAll('#practiceType .toggle-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active')}function setShotShape(b){document.querySelectorAll('#shotShape .toggle-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active')}function addCount(t){practiceData[t]=(practiceData[t]||0)+1;document.getElementById('cnt-'+t).textContent=practiceData[t]}function resetPractice(){practiceData={good:0,left:0,right:0,short:0,long:0};Object.keys(practiceData).forEach(k=>document.getElementById('cnt-'+k).textContent=0)}function savePractice(){let h=JSON.parse(localStorage.getItem('drcPractice')||'[]');h.unshift({date:new Date().toLocaleDateString(),data:{...practiceData},note:document.getElementById('practiceNote').value});localStorage.setItem('drcPractice',JSON.stringify(h.slice(0,20)))}
const WARMUP_STEPS=[['Loosen Up','Light mobility. Easy torso turns — no forced twisting.'],['Practice Swings','10 smooth practice swings. Build rhythm, not speed.'],['Short Wedges','5–7 balls. Start with half-swings and solid contact.'],['Mid Irons','5 balls with a 7 or 8 iron. Smooth full swings.'],['Driver / Woods','3–5 balls. Finish long clubs and build confidence.'],['Chipping','A few chips to check strike and landing feel.'],['Putting','Roll putts for speed first, then start line.'],['Ready','Warm-up complete. Use your normal pre-shot routine.']];function renderWarmup(){let html='';WARMUP_STEPS.forEach((s,i)=>html+='<div class="step-item'+(warmupState[i]?' done':'')+'" onclick="toggleWarmup('+i+')"><div class="step-check">'+(warmupState[i]?'✓':'')+'</div><div><div class="step-text">'+s[0]+'</div><div>'+s[1]+'</div></div></div>');document.getElementById('warmupSteps').innerHTML=html;let d=warmupState.filter(Boolean).length;document.getElementById('warmupProgress').style.width=d/8*100+'%';document.getElementById('warmupCount').textContent=d+' / 8 complete';let safe=document.getElementById('warmupSafety');if(!safe){safe=document.createElement('div');safe.id='warmupSafety';safe.className='card warmup-safety';document.getElementById('warmupSteps').insertAdjacentElement('afterend',safe)}safe.innerHTML='<b>FORM & SAFETY</b><br>Keep your core lightly engaged during turns and practice swings. Never jerk or force your spine into a twist. If you feel sharp pain in your shoulders or lower back, reduce the movement or skip that exercise.'}function toggleWarmup(i){warmupState[i]=!warmupState[i];renderWarmup()}function resetWarmup(){warmupState=Array(8).fill(false);renderWarmup()}
function renderRoutine(){let saved=JSON.parse(localStorage.getItem('drcRoutine')||'["","","",""]');while(saved.length<4)saved.push("");document.getElementById('routineFields').innerHTML=saved.slice(0,4).map((v,i)=>'<label class="routine-field"><span class="routine-num">'+(i+1)+'</span><input id="routine-'+i+'" value="'+String(v).replace(/"/g,'&quot;')+'" placeholder="Your step"></label>').join('')}function saveRoutine(){let r=[0,1,2,3].map(i=>document.getElementById('routine-'+i)?.value.trim()||'');localStorage.setItem('drcRoutine',JSON.stringify(r));let e=document.getElementById('routineSaved');if(e)e.textContent='✓ Routine saved'}function resetRoutine(){localStorage.removeItem('drcRoutine');renderRoutine()}function toggleAntiglare(){document.body.classList.toggle('antiglare');let on=document.body.classList.contains('antiglare');localStorage.setItem('drcAntiglare',on?'1':'0');let b=document.getElementById('antiGlareBtn');if(b)b.textContent=on?'ON':'OFF'}
(function(){if(localStorage.getItem('drcAntiglare')==='1')document.body.classList.add('antiglare');startGPS();let h=new Date().getHours(),g=h<12?'Good morning':h<17?'Good afternoon':'Good evening';document.getElementById('homeGreeting').textContent=g+', '+settings.player;updateWeatherDisplay()})();
function updateWindMarker(){
 let el=document.getElementById('windMarker'),ar=document.getElementById('windArrow'),tx=document.getElementById('windMarkerText');if(!el||!ar||!tx)return;
 let d=String(selectedWindDir||'').toUpperCase(),deg=0,label=d||'WIND';
 if(d==='HEAD'||d==='N'){deg=180;label='HEAD'}else if(d==='TAIL'||d==='S'){deg=0;label='TAIL'}else if(d.includes('L')&&d.includes('R')){deg=d.indexOf('L')<d.indexOf('R')?90:-90;label=d.indexOf('L')<d.indexOf('R')?'L→R':'R→L'}
 ar.style.transform='rotate('+deg+'deg)';tx.textContent=(weatherWind||0)+' km/h '+label;
}

function applyAdviceOnly(){let on=localStorage.getItem('drcAdviceOnly')==='1';document.body.classList.toggle('advice-only',on);let b=document.getElementById('adviceOnlyBtn');if(b)b.textContent=on?'ON':'OFF'}
function toggleAdviceOnly(){let on=localStorage.getItem('drcAdviceOnly')!=='1';localStorage.setItem('drcAdviceOnly',on?'1':'0');applyAdviceOnly()}
applyAdviceOnly();

function previewScorecard(input){
 const img=document.getElementById('scorecardPreview'),st=document.getElementById('scanStatus');
 const f=input&&input.files&&input.files[0]; if(!f){if(st)st.textContent='No scorecard selected';return}
 if(img){img.src=URL.createObjectURL(f);img.style.display='block'}
 if(st)st.textContent='Scorecard ready to check';
}

function drcShotBrief(distance,lie,windDir,pin){
  const d=Number(distance)||0, w=Number(weatherWind)||0;
  let play=d, reason=[];
  const wd=String(windDir||'').toUpperCase(), l=String(lie||'Fairway');
  if(wd.includes('HEAD')){play+=w*.8;reason.push('wind into you')}
  else if(wd.includes('TAIL')){play-=w*.5;reason.push('wind helping')}
  if(/DEEP ROUGH/i.test(l)){play+=8;reason.push('deep rough')}
  else if(/LIGHT ROUGH|ROUGH/i.test(l)){play+=4;reason.push('rough')}
  if(/BACK/i.test(pin||'')){play+=5;reason.push('back pin')}
  else if(/FRONT/i.test(pin||'')){play-=4;reason.push('front pin')}
  play=Math.max(1,Math.round(play));
  const club=nearestClub(play);
  const cross=wd.includes('L')&&wd.includes('R')?(wd.indexOf('L')<wd.indexOf('R')?' Allow for left-to-right wind.':' Allow for right-to-left wind.'):'';
  return play+' '+(units==='YARDS'?'yards':'metres')+' playing distance. '+club+'. '+(reason.length?'Allow for '+reason.join(', ')+'. ':'')+cross+drcResultAdjustment()+' Make your normal swing.';
}

function giveRoundAdvice(){
 const d=(typeof distance!=='undefined'&&distance)||document.getElementById('manualDistance')?.value||0;
 const pin=document.getElementById('pinPosition')?.value||'Center';
 const msg=drcShotBrief(d,selectedLie,selectedWindDir,pin);
 const el=document.getElementById('roundAdviceText');if(el)el.textContent=msg;
 if(typeof speak==='function')speak(msg);
}

function rememberShotResult(result){
 localStorage.setItem('drcLastShotResult',String(result||'').toUpperCase());
}
function drcResultAdjustment(){
 const r=localStorage.getItem('drcLastShotResult')||'';
 if(r==='SHORT')return ' Last shot finished short; confirm strike and consider one more club.';
 if(r==='LONG')return ' Last shot finished long; consider one less club if conditions are unchanged.';
 if(r==='LEFT')return ' Last shot missed left; keep the same routine and check start line.';
 if(r==='RIGHT')return ' Last shot missed right; keep the same routine and check start line.';
 return '';
}

async function fetchLiveWind(){
 if(gpsLat==null||gpsLon==null)return;
 try{
  const url='https://api.open-meteo.com/v1/forecast?latitude='+gpsLat+'&longitude='+gpsLon+'&current=temperature_2m,wind_speed_10m,wind_direction_10m&wind_speed_unit=kmh';
  const r=await fetch(url); if(!r.ok)throw new Error('weather');
  const j=await r.json(),c=j.current||{};
  if(Number.isFinite(Number(c.temperature_2m)))weatherTemp=Number(c.temperature_2m);
  if(Number.isFinite(Number(c.wind_speed_10m)))weatherWind=Number(c.wind_speed_10m);
  if(Number.isFinite(Number(c.wind_direction_10m)))weatherWindDir=Number(c.wind_direction_10m);
  updateWeatherDisplay();updateWindMarker();
 }catch(e){}
}
